// @generated by schema-rust from an authority-verified bootstrap Interface

pub struct z2VKw6 {}
pub struct z2Vb98(std::string::String);
impl z2Vb98 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2Vdno(std::string::String);
impl z2Vdno {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VT5W ( z2Vdno ,) ;
pub struct z2VUoM {
    pub field_0: z2Vdno,
    pub field_1: z2VQu1,
    pub field_2: z2VQyu,
    pub field_3: z2Veh3,
}
pub struct z2VXqz {}
pub struct z2VVnv {
    pub field_0: z2VQEC,
    pub field_1: z2VaXy,
}
pub enum z2VZMF {z2VNWD , z2VMBK ,} 
pub struct z2VauH ( z2Vdno ,) ;
pub struct z2VaXy(std::string::String);
impl z2VaXy {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VTjG ( z2VMcF ,) ;
pub enum z2VQEC {z2VX94 , z2Vcbb , z2VNMC , z2VXk7 , z2VXbF ,} 
pub enum z2Veh3 {z2VSU1 ( z2VTjG ,) , z2Vezi , z2VevM ( z2VasX ,) , z2VRsH ( z2VavG ,) ,} 
pub enum z2VR8j {z2Vaof , z2VM9z , z2VWhQ , z2VWNS , z2VZLk ,} 
pub struct z2VPds ( z2Vdno ,) ;
pub enum z2VU7B {z2VZYM ( z2VauH ,) , z2VXhH ( z2VKw6 ,) , z2VYfv ( z2VNNt ,) , z2Vf8q ( z2VXqz ,) , z2VWwB ( z2VX7d ,) ,} 
pub struct z2VQyu(std::string::String);
impl z2VQyu {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VQtu ( z2Vdno ,) ;
pub enum z2VLHo {z2VcaY ,} 
pub struct z2VX7d ( z2VUoM ,) ;
pub struct z2VTH3(std::string::String);
impl z2VTH3 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VMcF(std::string::String);
impl z2VMcF {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VQu1(std::string::String);
impl z2VQu1 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VNNt ( z2Vdno ,) ;
pub struct z2VasX ( z2VTH3 ,) ;
pub struct z2VavG ( z2Vb98 ,) ;
pub struct z2Vd3L ( z2VZMF ,) ;
pub struct z2VXQT {
    pub field_0: z2VR8j,
    pub field_1: z2VLHo,
}
pub enum z2VUiq {z2VQeG ( z2VT5W ,) , z2VRjY ( z2Vd3L ,) , z2VV4U ( z2Vd3L ,) , z2VWXh ( z2VPds ,) , z2VUhK ( z2VQtu ,) , z2VehS ( z2VXQT ,) , z2Va1P ( z2VVnv ,) ,} 
