// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
pub use dotos::{DotosDecodeError, DotosEncode, DotosSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProviderName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EndpointUrl(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ModelName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EnvironmentVariable(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GopassPath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SecretFilePath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectionDetail(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EnvironmentSecret(EnvironmentVariable);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GopassSecret(GopassPath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FileSecret(SecretFilePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SecretSource {
    Environment(EnvironmentSecret),
    Gopass(GopassSecret),
    File(FileSecret),
    NoSecret,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProviderConfiguration {
    pub provider_name: ProviderName,
    pub endpoint_url: EndpointUrl,
    pub model_name: ModelName,
    pub secret_source: SecretSource,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ConfigureProviderPayload(ProviderConfiguration);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetireProviderPayload(ProviderName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SetDefaultProviderPayload(ProviderName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StartPayload {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StopPayload {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProviderConfiguredPayload(ProviderName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProviderRetiredPayload(ProviderName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DefaultProviderSetPayload(ProviderName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum LifecycleState {
    Started,
    Stopped,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Lifecycle(LifecycleState);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OrderRejectionReason {
    ProviderUnknown,
    ProviderAlreadyConfigured,
    EndpointInvalid,
    SecretUnavailable,
    PolicyStoreUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OrderRejection {
    pub order_rejection_reason: OrderRejectionReason,
    pub rejection_detail: RejectionDetail,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OperationKind {
    ConfigureProvider,
    RetireProvider,
    SetDefaultProvider,
    Start,
    Stop,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum UnimplementedReason {
    NotInPrototypeScope,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestUnimplementedPayload {
    pub operation_kind: OperationKind,
    pub unimplemented_reason: UnimplementedReason,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    ConfigureProvider(ConfigureProviderPayload),
    RetireProvider(RetireProviderPayload),
    SetDefaultProvider(SetDefaultProviderPayload),
    Start(StartPayload),
    Stop(StopPayload),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ProviderConfigured(ProviderConfiguredPayload),
    ProviderRetired(ProviderRetiredPayload),
    DefaultProviderSet(DefaultProviderSetPayload),
    Started(Lifecycle),
    Stopped(Lifecycle),
    OrderRejected(OrderRejection),
    RequestUnimplemented(RequestUnimplementedPayload),
}

#[rustfmt::skip]
impl ProviderName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ProviderName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EndpointUrl {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for EndpointUrl {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ModelName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ModelName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EnvironmentVariable {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for EnvironmentVariable {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GopassPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for GopassPath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SecretFilePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SecretFilePath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RejectionDetail {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RejectionDetail {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EnvironmentSecret {
    pub fn new(payload: EnvironmentVariable) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &EnvironmentVariable {
        &self.0
    }
    pub fn into_payload(self) -> EnvironmentVariable {
        self.0
    }
}
#[rustfmt::skip]
impl From<EnvironmentVariable> for EnvironmentSecret {
    fn from(payload: EnvironmentVariable) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GopassSecret {
    pub fn new(payload: GopassPath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &GopassPath {
        &self.0
    }
    pub fn into_payload(self) -> GopassPath {
        self.0
    }
}
#[rustfmt::skip]
impl From<GopassPath> for GopassSecret {
    fn from(payload: GopassPath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl FileSecret {
    pub fn new(payload: SecretFilePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SecretFilePath {
        &self.0
    }
    pub fn into_payload(self) -> SecretFilePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<SecretFilePath> for FileSecret {
    fn from(payload: SecretFilePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ConfigureProviderPayload {
    pub fn new(payload: ProviderConfiguration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProviderConfiguration {
        &self.0
    }
    pub fn into_payload(self) -> ProviderConfiguration {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProviderConfiguration> for ConfigureProviderPayload {
    fn from(payload: ProviderConfiguration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetireProviderPayload {
    pub fn new(payload: ProviderName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProviderName {
        &self.0
    }
    pub fn into_payload(self) -> ProviderName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProviderName> for RetireProviderPayload {
    fn from(payload: ProviderName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SetDefaultProviderPayload {
    pub fn new(payload: ProviderName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProviderName {
        &self.0
    }
    pub fn into_payload(self) -> ProviderName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProviderName> for SetDefaultProviderPayload {
    fn from(payload: ProviderName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ProviderConfiguredPayload {
    pub fn new(payload: ProviderName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProviderName {
        &self.0
    }
    pub fn into_payload(self) -> ProviderName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProviderName> for ProviderConfiguredPayload {
    fn from(payload: ProviderName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ProviderRetiredPayload {
    pub fn new(payload: ProviderName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProviderName {
        &self.0
    }
    pub fn into_payload(self) -> ProviderName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProviderName> for ProviderRetiredPayload {
    fn from(payload: ProviderName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DefaultProviderSetPayload {
    pub fn new(payload: ProviderName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProviderName {
        &self.0
    }
    pub fn into_payload(self) -> ProviderName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProviderName> for DefaultProviderSetPayload {
    fn from(payload: ProviderName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Lifecycle {
    pub fn new(payload: LifecycleState) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &LifecycleState {
        &self.0
    }
    pub fn into_payload(self) -> LifecycleState {
        self.0
    }
}
#[rustfmt::skip]
impl From<LifecycleState> for Lifecycle {
    fn from(payload: LifecycleState) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SecretSource {
    pub fn environment(payload: EnvironmentVariable) -> Self {
        Self::Environment(EnvironmentSecret::new(payload))
    }
    pub fn gopass(payload: GopassPath) -> Self {
        Self::Gopass(GopassSecret::new(payload))
    }
    pub fn file(payload: SecretFilePath) -> Self {
        Self::File(FileSecret::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn configure_provider(payload: ProviderConfiguration) -> Self {
        Self::ConfigureProvider(ConfigureProviderPayload::new(payload))
    }
    pub fn retire_provider(payload: ProviderName) -> Self {
        Self::RetireProvider(RetireProviderPayload::new(payload))
    }
    pub fn set_default_provider(payload: ProviderName) -> Self {
        Self::SetDefaultProvider(SetDefaultProviderPayload::new(payload))
    }
    pub fn start(payload: StartPayload) -> Self {
        Self::Start(payload)
    }
    pub fn stop(payload: StopPayload) -> Self {
        Self::Stop(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn provider_configured(payload: ProviderName) -> Self {
        Self::ProviderConfigured(ProviderConfiguredPayload::new(payload))
    }
    pub fn provider_retired(payload: ProviderName) -> Self {
        Self::ProviderRetired(ProviderRetiredPayload::new(payload))
    }
    pub fn default_provider_set(payload: ProviderName) -> Self {
        Self::DefaultProviderSet(DefaultProviderSetPayload::new(payload))
    }
    pub fn started(payload: LifecycleState) -> Self {
        Self::Started(Lifecycle::new(payload))
    }
    pub fn stopped(payload: LifecycleState) -> Self {
        Self::Stopped(Lifecycle::new(payload))
    }
    pub fn order_rejected(payload: OrderRejection) -> Self {
        Self::OrderRejected(payload)
    }
    pub fn request_unimplemented(payload: RequestUnimplementedPayload) -> Self {
        Self::RequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
impl From<EnvironmentSecret> for SecretSource {
    fn from(payload: EnvironmentSecret) -> Self {
        Self::Environment(payload)
    }
}

#[rustfmt::skip]
impl From<GopassSecret> for SecretSource {
    fn from(payload: GopassSecret) -> Self {
        Self::Gopass(payload)
    }
}

#[rustfmt::skip]
impl From<FileSecret> for SecretSource {
    fn from(payload: FileSecret) -> Self {
        Self::File(payload)
    }
}

#[rustfmt::skip]
impl From<ConfigureProviderPayload> for Input {
    fn from(payload: ConfigureProviderPayload) -> Self {
        Self::ConfigureProvider(payload)
    }
}

#[rustfmt::skip]
impl From<RetireProviderPayload> for Input {
    fn from(payload: RetireProviderPayload) -> Self {
        Self::RetireProvider(payload)
    }
}

#[rustfmt::skip]
impl From<SetDefaultProviderPayload> for Input {
    fn from(payload: SetDefaultProviderPayload) -> Self {
        Self::SetDefaultProvider(payload)
    }
}

#[rustfmt::skip]
impl From<StartPayload> for Input {
    fn from(payload: StartPayload) -> Self {
        Self::Start(payload)
    }
}

#[rustfmt::skip]
impl From<StopPayload> for Input {
    fn from(payload: StopPayload) -> Self {
        Self::Stop(payload)
    }
}

#[rustfmt::skip]
impl From<ProviderConfiguredPayload> for Output {
    fn from(payload: ProviderConfiguredPayload) -> Self {
        Self::ProviderConfigured(payload)
    }
}

#[rustfmt::skip]
impl From<ProviderRetiredPayload> for Output {
    fn from(payload: ProviderRetiredPayload) -> Self {
        Self::ProviderRetired(payload)
    }
}

#[rustfmt::skip]
impl From<DefaultProviderSetPayload> for Output {
    fn from(payload: DefaultProviderSetPayload) -> Self {
        Self::DefaultProviderSet(payload)
    }
}

#[rustfmt::skip]
impl From<OrderRejection> for Output {
    fn from(payload: OrderRejection) -> Self {
        Self::OrderRejected(payload)
    }
}

#[rustfmt::skip]
impl From<RequestUnimplementedPayload> for Output {
    fn from(payload: RequestUnimplementedPayload) -> Self {
        Self::RequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::str::FromStr for Input {
    type Err = DotosDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        DotosSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as DotosEncode>::to_dotos(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::str::FromStr for Output {
    type Err = DotosDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        DotosSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as DotosEncode>::to_dotos(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_CONFIGURE_PROVIDER: u64 = 0x0000000100000002;
    pub const INPUT_RETIRE_PROVIDER: u64 = 0x0001000100000002;
    pub const INPUT_SET_DEFAULT_PROVIDER: u64 = 0x0002000100000002;
    pub const INPUT_START: u64 = 0x0003000100000002;
    pub const INPUT_STOP: u64 = 0x0004000100000002;
    pub const OUTPUT_PROVIDER_CONFIGURED: u64 = 0x0100000100000002;
    pub const OUTPUT_PROVIDER_RETIRED: u64 = 0x0101000100000002;
    pub const OUTPUT_DEFAULT_PROVIDER_SET: u64 = 0x0102000100000002;
    pub const OUTPUT_STARTED: u64 = 0x0103000100000002;
    pub const OUTPUT_STOPPED: u64 = 0x0104000100000002;
    pub const OUTPUT_ORDER_REJECTED: u64 = 0x0105000100000002;
    pub const OUTPUT_REQUEST_UNIMPLEMENTED: u64 = 0x0106000100000002;
    pub const HANDSHAKE_REQUEST: u64 = 0xFF00000100000002;
    pub const HANDSHAKE_REPLY: u64 = 0xFF01000100000002;
    pub const ENGINE_REFUSAL: u64 = 0xFF02000100000002;
}

#[rustfmt::skip]
pub enum ContractMarker {}
#[rustfmt::skip]
impl signal_frame::WireContract for ContractMarker {
    const BINDING: signal_frame::ContractBinding = signal_frame::ContractBinding::new(
        match signal_frame::ContractId::try_new(2u32) {
            Ok(contract) => contract,
            Err(_) => panic!("generated contract ID must be nonzero"),
        },
        match signal_frame::WireRevision::try_new(1u16) {
            Ok(revision) => revision,
            Err(_) => panic!("generated wire revision must be nonzero"),
        },
    );
}
#[rustfmt::skip]
/// Why the daemon refused to produce an ordinary reply.
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq
)]
pub enum EngineRefusalReason {
    /// The engine ran and rejected the request with its typed
    /// domain error; the rendered error text is the detail.
    Rejected,
    /// The engine layer could not serve the request at all.
    Unavailable,
}
#[rustfmt::skip]
impl std::fmt::Display for EngineRefusalReason {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Rejected => formatter.write_str("engine rejected the request"),
            Self::Unavailable => formatter.write_str("engine unavailable"),
        }
    }
}
#[rustfmt::skip]
/// The refusal reply a daemon writes when the engine failed, so
/// the caller receives a complete typed frame instead of a closed
/// socket it cannot distinguish from daemon death. The typed
/// engine error stays daemon-side; the wire carries the
/// classification plus the rendered error text.
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineRefusal {
    pub reason: EngineRefusalReason,
    pub detail: String,
}
#[rustfmt::skip]
impl EngineRefusal {
    pub fn rejected(detail: String) -> Self {
        Self {
            reason: EngineRefusalReason::Rejected,
            detail,
        }
    }
    pub fn unavailable(detail: String) -> Self {
        Self {
            reason: EngineRefusalReason::Unavailable,
            detail,
        }
    }
    pub fn encode_bound_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            signal_frame::SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&short_header::ENGINE_REFUSAL.to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    FrameEncode,
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    LegacyHeader { contract_id: u32, wire_revision: u16 },
    ContractMismatch { expected: u32, found: u32 },
    UnsupportedWireRevision { contract_id: u32, expected: u16, found: u16 },
    UnknownRoute { root: u8, variant: u8 },
    RouteBodyMismatch { root: u8, variant: u8, body: &'static str },
    UnexpectedFrameBody { found: &'static str },
    OperationCount { found: usize },
    EngineRefused { refusal: EngineRefusal },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::FrameEncode => {
                formatter.write_str("failed to encode bound signal frame")
            }
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::LegacyHeader { contract_id, wire_revision } => {
                write!(
                    formatter,
                    "legacy unbound signal frame ({contract_id}, {wire_revision})"
                )
            }
            Self::ContractMismatch { expected, found } => {
                write!(
                    formatter,
                    "signal contract mismatch: expected {expected}, found {found}"
                )
            }
            Self::UnsupportedWireRevision { contract_id, expected, found } => {
                write!(
                    formatter,
                    "unsupported wire revision for contract {contract_id}: expected {expected}, found {found}"
                )
            }
            Self::UnknownRoute { root, variant } => {
                write!(formatter, "unknown bound signal route ({root}, {variant})")
            }
            Self::RouteBodyMismatch { root, variant, body } => {
                write!(
                    formatter,
                    "bound signal route ({root}, {variant}) does not carry {body}"
                )
            }
            Self::UnexpectedFrameBody { found } => {
                write!(formatter, "expected one request frame, found {found}")
            }
            Self::OperationCount { found } => {
                write!(formatter, "expected one request operation, found {found}")
            }
            Self::EngineRefused { refusal } => {
                write!(formatter, "{}: {}", refusal.reason, refusal.detail)
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}
#[rustfmt::skip]
impl ContractMarker {
    pub fn handshake_request_frame(request: signal_frame::HandshakeRequest) -> Frame {
        Frame::new(
            signal_frame::WireRoute::new(
                signal_frame::RootCode::new(0xff),
                signal_frame::VariantCode::new(0),
            ),
            FrameBody::HandshakeRequest(request),
        )
    }
    pub fn handshake_reply_frame(reply: signal_frame::HandshakeReply) -> Frame {
        Frame::new(
            signal_frame::WireRoute::new(
                signal_frame::RootCode::new(0xff),
                signal_frame::VariantCode::new(1),
            ),
            FrameBody::HandshakeReply(reply),
        )
    }
    pub fn decode_frame(bytes: &[u8]) -> Result<Frame, SignalFrameError> {
        if bytes.len() < signal_frame::SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: bytes.len(),
            });
        }
        let mut header_bytes = [0_u8; signal_frame::SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&bytes[..signal_frame::SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let contract_id = header as u32;
        let wire_revision = (header >> 32) as u16;
        if contract_id == 0 || wire_revision == 0 {
            return Err(SignalFrameError::LegacyHeader {
                contract_id,
                wire_revision,
            });
        }
        if contract_id != 2u32 {
            return Err(SignalFrameError::ContractMismatch {
                expected: 2u32,
                found: contract_id,
            });
        }
        if wire_revision != 1u16 {
            return Err(SignalFrameError::UnsupportedWireRevision {
                contract_id,
                expected: 1u16,
                found: wire_revision,
            });
        }
        let root = (header >> 56) as u8;
        let variant = (header >> 48) as u8;
        match (root, variant) {
            (0, 0)
            | (0, 1)
            | (0, 2)
            | (0, 3)
            | (0, 4)
            | (1, 0)
            | (1, 1)
            | (1, 2)
            | (1, 3)
            | (1, 4)
            | (1, 5)
            | (1, 6)
            | (0xff, 0)
            | (0xff, 1)
            | (0xff, 2) => {}
            _ => {
                return Err(SignalFrameError::UnknownRoute {
                    root,
                    variant,
                });
            }
        }
        if (root, variant) == (0xff, 2) {
            let refusal = rkyv::from_bytes::<
                EngineRefusal,
                rkyv::rancor::Error,
            >(&bytes[signal_frame::SHORT_HEADER_BYTE_COUNT..])
                .map_err(|_| SignalFrameError::ArchiveDecode)?;
            return Err(SignalFrameError::EngineRefused {
                refusal,
            });
        }
        let frame = Frame::decode(bytes).map_err(|_| SignalFrameError::ArchiveDecode)?;
        let header_route = signal_frame::WireRoute::new(
            signal_frame::RootCode::new(root),
            signal_frame::VariantCode::new(variant),
        );
        let body_matches = match frame.body() {
            FrameBody::HandshakeRequest(_) => (root, variant) == (0xff, 0),
            FrameBody::HandshakeReply(_) => (root, variant) == (0xff, 1),
            FrameBody::Request { request, .. } => {
                request.route().is_ok_and(|route| route == header_route)
            }
            FrameBody::Reply { reply, .. } => {
                match reply {
                    signal_frame::Reply::Accepted { per_operation, .. } => {
                        match per_operation.head() {
                            signal_frame::SubReply::Ok(output) => {
                                output.wire_route() == header_route
                            }
                            signal_frame::SubReply::Failed {
                                detail: Some(output),
                                ..
                            } => output.wire_route() == header_route,
                            signal_frame::SubReply::Invalidated
                            | signal_frame::SubReply::Failed { detail: None, .. }
                            | signal_frame::SubReply::Skipped => root == 1,
                        }
                    }
                    signal_frame::Reply::Rejected { .. } => root == 1,
                }
            }
        };
        if !body_matches {
            let body = match frame.body() {
                FrameBody::HandshakeRequest(_) => "handshake request",
                FrameBody::HandshakeReply(_) => "handshake reply",
                FrameBody::Request { .. } => "request",
                FrameBody::Reply { .. } => "reply",
            };
            return Err(SignalFrameError::RouteBodyMismatch {
                root,
                variant,
                body,
            });
        }
        Ok(frame)
    }
    pub fn decode_single_request(
        bytes: &[u8],
    ) -> Result<(signal_frame::ExchangeIdentifier, Input), SignalFrameError> {
        let frame = Self::decode_frame(bytes)?;
        match frame.into_body() {
            FrameBody::Request { exchange, request } => {
                let found = request.payloads().len();
                if found != 1 {
                    return Err(SignalFrameError::OperationCount {
                        found,
                    });
                }
                Ok((exchange, request.payloads.into_head()))
            }
            FrameBody::HandshakeRequest(_) => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "handshake request",
                })
            }
            FrameBody::HandshakeReply(_) => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "handshake reply",
                })
            }
            FrameBody::Reply { .. } => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "reply",
                })
            }
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    ConfigureProvider,
    RetireProvider,
    SetDefaultProvider,
    Start,
    Stop,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    ProviderConfigured,
    ProviderRetired,
    DefaultProviderSet,
    Started,
    Stopped,
    OrderRejected,
    RequestUnimplemented,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::ConfigureProvider(_) => InputRoute::ConfigureProvider,
            Self::RetireProvider(_) => InputRoute::RetireProvider,
            Self::SetDefaultProvider(_) => InputRoute::SetDefaultProvider,
            Self::Start(_) => InputRoute::Start,
            Self::Stop(_) => InputRoute::Stop,
        }
    }
    pub fn wire_route(&self) -> signal_frame::WireRoute {
        match self {
            Self::ConfigureProvider(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(0),
                )
            }
            Self::RetireProvider(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(1),
                )
            }
            Self::SetDefaultProvider(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(2),
                )
            }
            Self::Start(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(3),
                )
            }
            Self::Stop(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(4),
                )
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::ConfigureProvider(_) => short_header::INPUT_CONFIGURE_PROVIDER,
            Self::RetireProvider(_) => short_header::INPUT_RETIRE_PROVIDER,
            Self::SetDefaultProvider(_) => short_header::INPUT_SET_DEFAULT_PROVIDER,
            Self::Start(_) => short_header::INPUT_START,
            Self::Stop(_) => short_header::INPUT_STOP,
        }
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::ProviderConfigured(_) => OutputRoute::ProviderConfigured,
            Self::ProviderRetired(_) => OutputRoute::ProviderRetired,
            Self::DefaultProviderSet(_) => OutputRoute::DefaultProviderSet,
            Self::Started(_) => OutputRoute::Started,
            Self::Stopped(_) => OutputRoute::Stopped,
            Self::OrderRejected(_) => OutputRoute::OrderRejected,
            Self::RequestUnimplemented(_) => OutputRoute::RequestUnimplemented,
        }
    }
    pub fn wire_route(&self) -> signal_frame::WireRoute {
        match self {
            Self::ProviderConfigured(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(0),
                )
            }
            Self::ProviderRetired(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(1),
                )
            }
            Self::DefaultProviderSet(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(2),
                )
            }
            Self::Started(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(3),
                )
            }
            Self::Stopped(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(4),
                )
            }
            Self::OrderRejected(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(5),
                )
            }
            Self::RequestUnimplemented(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(6),
                )
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::ProviderConfigured(_) => short_header::OUTPUT_PROVIDER_CONFIGURED,
            Self::ProviderRetired(_) => short_header::OUTPUT_PROVIDER_RETIRED,
            Self::DefaultProviderSet(_) => short_header::OUTPUT_DEFAULT_PROVIDER_SET,
            Self::Started(_) => short_header::OUTPUT_STARTED,
            Self::Stopped(_) => short_header::OUTPUT_STOPPED,
            Self::OrderRejected(_) => short_header::OUTPUT_ORDER_REJECTED,
            Self::RequestUnimplemented(_) => short_header::OUTPUT_REQUEST_UNIMPLEMENTED,
        }
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "ConfigureProvider",
        "RetireProvider",
        "SetDefaultProvider",
        "Start",
        "Stop",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        let route = self.wire_route();
        u64::from(route.root().value()) | (u64::from(route.variant().value()) << 8)
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::BoundExchangeFrame<ContractMarker, Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let route = self.wire_route();
        let request = signal_frame::Request::from_payload(self);
        Frame::new(
            route,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
    pub fn encode_request_frame(
        self,
        exchange: signal_frame::ExchangeIdentifier,
    ) -> Result<Vec<u8>, SignalFrameError> {
        self.into_frame(exchange).encode().map_err(|_| SignalFrameError::FrameEncode)
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let route = self.wire_route();
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::new(
            route,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
    pub fn encode_reply_frame(
        self,
        exchange: signal_frame::ExchangeIdentifier,
    ) -> Result<Vec<u8>, SignalFrameError> {
        self.into_reply_frame(exchange)
            .encode()
            .map_err(|_| SignalFrameError::FrameEncode)
    }
}
